#!/bin/bash 
#SBATCH --job-name=main_3x4  ### name your job 
#SBATCH --time=00:30:00		 ### hh:mm:ss or dd-hh:mm:ss
#SBATCH --mem=48G			 ### memory setting is max @ 4 GB per core
#SBATCH --ntasks=13			 ### launch 13 process
#SBATCH --cpus-per-task=1	 ### single-threaded processes
#SBATCH --ntasks-per-node=13 ### 13 per node

#SBATCH --partition=short,comp,gpu

#SBATCH --output=main_3x4.%j.out

module load openmpi/3.1.4-mlx

make ALL

mpirun mainOut 3 4 6000 100