#!/bin/bash 
#SBATCH --job-name=main ### name your job 
#SBATCH --time=00:30:00		 ### hh:mm:ss or dd-hh:mm:ss
#SBATCH --mem=36G				 ### memory setting is max @ 4 GB per core
#SBATCH --ntasks=9			 ### launch 9 process
#SBATCH --cpus-per-task=1		 ### single-threaded processes
#SBATCH --ntasks-per-node=9   ### 9 per node

#SBATCH --partition=short,comp,gpu

#SBATCH --output=main.%j.out

module load openmpi/3.1.6-ucx

make ALL

mpirun mainOut