#!/bin/bash 
#SBATCH --job-name=main_2x3  ### name your job 
#SBATCH --time=00:30:00		 ### hh:mm:ss or dd-hh:mm:ss
#SBATCH --mem=28G		     ### memory setting is max @ 4 GB per core
#SBATCH --ntasks=7			 ### launch 7 process
#SBATCH --cpus-per-task=1    ### single-threaded processes
#SBATCH --ntasks-per-node=7  ### 7 per node

#SBATCH --partition=short,comp,gpu

#SBATCH --output=main_2x3.%j.out

module load openmpi/3.1.4-mlx

make ALL

mpirun mainOut 2 3 6000 100